/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d532ccc1-9110-46c9-b788-e3fe9910a69e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_kmKtTcdLe",
    "aws_user_pools_web_client_id": "2ilnqa64cnufpo2p7li5fec7uk",
    "oauth": {}
};


export default awsmobile;
